=== moliva/proactive/src/Core/org/objectweb/proactive/core/component/config/component-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="componentConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="controllers"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="controllers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="controller"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="controller">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="interface"/>
        <xs:element ref="implementation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="interface" type="xs:string"/>
  <xs:element name="implementation" type="xs:string"/>
</xs:schema>

=== moliva/proactive/src/Tests/functionalTests/component/conform/membranes/flatParametricPrimitiveTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentConfiguration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="component-config.xsd"
	name="defaultConfiguration">
	<!--  This is the default configuration file for the controllers and interceptors of a **primitive** component in the proactive implementation.-->
	<controllers>
		<!-- need to add the factory itf -->
		<controller>
			<interface>
				org.objectweb.proactive.core.component.control.PABindingController
			</interface>
			<implementation>
				org.objectweb.proactive.core.component.control.PABindingControllerImpl
			</implementation>
		</controller>
		<controller>
			<interface>
				org.objectweb.proactive.core.component.control.PAGCMLifeCycleController
			</interface>
			<implementation>
				org.objectweb.proactive.core.component.control.PAGCMLifeCycleControllerImpl
			</implementation>
		</controller>
		<controller>
			<interface>
				org.objectweb.fractal.api.control.NameController
			</interface>
			<implementation>
				org.objectweb.proactive.core.component.control.PANameControllerImpl
			</implementation>
		</controller>
		<controller>
			<interface>
				org.objectweb.proactive.core.component.control.PAMulticastController
			</interface>
			<implementation>
				org.objectweb.proactive.core.component.control.PAMulticastControllerImpl
			</implementation>
		</controller>
		<controller>
			<interface>
				org.etsi.uri.gcm.api.control.GathercastController
			</interface>
			<implementation>
				org.objectweb.proactive.core.component.control.PAGathercastControllerImpl
			</implementation>
		</controller>
        <controller>
            <interface>
		org.objectweb.proactive.core.component.control.PAMigrationController
            </interface>
            <implementation>
		org.objectweb.proactive.core.component.control.PAMigrationControllerImpl
            </implementation>
        </controller>
	</controllers>

</componentConfiguration>

=== moliva/proactive/src/Tests/functionalTests/component/interceptor/controllerobject/config/config-adl.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../org/objectweb/proactive/core/component/config/component-config.xsd" name="interception">
    <controllers>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PABindingController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PABindingControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAContentController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAContentControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAGCMLifeCycleController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAGCMLifeCycleControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PASuperController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PASuperControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.fractal.api.control.NameController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PANameControllerImpl</implementation>
        </controller>
        <!-- Specific controllers -->
        <controller>
            <interface>functionalTests.component.controller.DummyController</interface>
            <implementation>functionalTests.component.controller.DummyControllerImpl</implementation>
        </controller>
        <controller>
            <interface>functionalTests.component.interceptor.controllerobject.Interceptor1</interface>
            <implementation>functionalTests.component.interceptor.controllerobject.Interceptor1Impl</implementation>
        </controller>
        <controller>
            <interface>functionalTests.component.interceptor.controllerobject.Interceptor2</interface>
            <implementation>functionalTests.component.interceptor.controllerobject.Interceptor2Impl</implementation>
        </controller>
    </controllers>
</componentConfiguration>

=== moliva/proactive/src/Examples/org/objectweb/proactive/examples/documentation/components/component-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @snippet-start-with-header component_userguide_10 -->
<componentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../../../../Core/org/objectweb/proactive/core/component/config/component-config.xsd" 
    name="MyConfigurationName">
    <controllers>
        <controller>
            <interface>
                ControllerInterface
            </interface>
            <implementation>
                ControllerImplementation
            </implementation>
        </controller>
        <!-- other controllers -->
        <!-- @snippet-break component_userguide_10 -->
        <!-- @snippet-start component_userguide_13 -->
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAInterceptorController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAInterceptorControllerImpl</implementation>
        </controller>
        <!-- @snippet-end component_userguide_13 -->
        <!-- @snippet-resume component_userguide_10 -->
    </controllers>
</componentConfiguration>
<!-- @snippet-end component_userguide_10 -->

=== moliva/proactive/src/Core/org/objectweb/proactive/core/component/config/default-component-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<componentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="component-config.xsd"
 name="defaultConfiguration">
 <!--  This is the default configuration file for the controllers of a component in the proactive implementation.-->
    <controllers>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PABindingController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PABindingControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAContentController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAContentControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAGCMLifeCycleController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAGCMLifeCycleControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PASuperController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PASuperControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.fractal.api.control.NameController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PANameControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAMulticastController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAMulticastControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.etsi.uri.gcm.api.control.GathercastController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAGathercastControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.objectweb.proactive.core.component.control.PAMigrationController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAMigrationControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.etsi.uri.gcm.api.control.MonitorController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAMonitorControllerImpl</implementation>
        </controller>
        <controller>
            <interface>org.etsi.uri.gcm.api.control.PriorityController</interface>
            <implementation>org.objectweb.proactive.core.component.control.PAPriorityControllerImpl</implementation>
        </controller>
    </controllers>
</componentConfiguration>
